"""empty message

Revision ID: 119dfb180059
Revises: 5ae5d759f7af
Create Date: 2022-03-03 08:23:35.255453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119dfb180059'
down_revision = '5ae5d759f7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password_hash', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password_hash')
    # ### end Alembic commands ###
