"""empty message

Revision ID: 56f6e0920c2f
Revises: f8a3c4b4bce0
Create Date: 2022-03-03 20:47:34.877678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f6e0920c2f'
down_revision = 'f8a3c4b4bce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('firstName', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('lastName', sa.String(length=80), nullable=True))
    op.drop_column('user_profiles', 'first_name')
    op.drop_column('user_profiles', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'lastName')
    op.drop_column('user_profiles', 'firstName')
    # ### end Alembic commands ###
