"""empty message

Revision ID: f8a3c4b4bce0
Revises: 119dfb180059
Create Date: 2022-03-03 08:32:04.622504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a3c4b4bce0'
down_revision = '119dfb180059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('user_profiles', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
